### ISSUE TITLE
Issue writing 

### ISSUE THREAD

**Issue by ckcompton** [logicmonitor/lm-logs-fluentd#51]
`2022-09-29 12:30:28 -0500 [info]: #0 fluentd worker is now running worker=0
2022-09-29 12:30:29 -0500 [warn]: #0 got unrecoverable error in primary and no secondary error_class=NoMethodError error="undefined method `[]' for nil:NilClass"
  2022-09-29 12:30:29 -0500 [warn]: #0 C:/opt/td-agent/etc/td-agent/plugin/out_lm.rb:95:in `block (2 levels) in process_record'
  2022-09-29 12:30:29 -0500 [warn]: #0 C:/opt/td-agent/etc/td-agent/plugin/out_lm.rb:95:in `each'
  2022-09-29 12:30:29 -0500 [warn]: #0 C:/opt/td-agent/etc/td-agent/plugin/out_lm.rb:95:in `block in process_record'
  2022-09-29 12:30:29 -0500 [warn]: #0 C:/opt/td-agent/etc/td-agent/plugin/out_lm.rb:92:in `each'
  2022-09-29 12:30:29 -0500 [warn]: #0 C:/opt/td-agent/etc/td-agent/plugin/out_lm.rb:92:in `process_record'
  2022-09-29 12:30:29 -0500 [warn]: #0 C:/opt/td-agent/etc/td-agent/plugin/out_lm.rb:79:in `block in write'
  2022-09-29 12:30:29 -0500 [warn]: #0 C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.6/lib/fluent/event.rb:315:in `each'
  2022-09-29 12:30:29 -0500 [warn]: #0 C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.6/lib/fluent/event.rb:315:in `block in each'
  2022-09-29 12:30:29 -0500 [warn]: #0 C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.6/lib/fluent/plugin/buffer/memory_chunk.rb:81:in `open'
  2022-09-29 12:30:29 -0500 [warn]: #0 C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.6/lib/fluent/plugin/buffer/memory_chunk.rb:81:in `open'
  2022-09-29 12:30:29 -0500 [warn]: #0 C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.6/lib/fluent/event.rb:314:in `each'
  2022-09-29 12:30:29 -0500 [warn]: #0 C:/opt/td-agent/etc/td-agent/plugin/out_lm.rb:78:in `write'
  2022-09-29 12:30:29 -0500 [warn]: #0 C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.6/lib/fluent/compat/output.rb:131:in `write'
  2022-09-29 12:30:29 -0500 [warn]: #0 C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.6/lib/fluent/plugin/output.rb:1179:in `try_flush'
  2022-09-29 12:30:29 -0500 [warn]: #0 C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.6/lib/fluent/plugin/output.rb:1500:in `flush_thread_run'
  2022-09-29 12:30:29 -0500 [warn]: #0 C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.6/lib/fluent/plugin/output.rb:499:in `block (2 levels) in start'
  2022-09-29 12:30:29 -0500 [warn]: #0 C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.14.6/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2022-09-29 12:30:29 -0500 [warn]: #0 bad chunk is moved to /tmp/fluent/backup/worker0/object_adc/5e9d43bc8ee32a3ddd5938c455c11926.log
2022-09-29 12:30:30 -0500 [warn]: #0 got unrecoverable error in primary and no secondary error_class=NoMethodError error="undefined method `[]' for nil:NilClass"`

[td-agent.txt](https://github.com/logicmonitor/lm-logs-fluentd/files/9677793/td-agent.txt)

[logtile.txt](https://github.com/logicmonitor/lm-logs-fluentd/files/9677772/logtile.txt)

**Comment by siddharthck** [comment]
@ckcompton , I think you have not provided `resource_mapping` config correctly. 
If you want to force resource mapping, then you need to add below config using record transformer.

```
<source>
  @type tail
  tag lm.iis
  path C:/Program Files/LogicMonitor/Agent/logs/wrapper.log
  pos_file C:\Program Files\LogicMonitor\Agent\logs\logs.pos
  <parse>
    @type regexp
    expression /\[(?<time>\d{4}-\d{2}-\d{2} [\d:]+)(?<message>.+)/
    time_format %Y-%m-%d %H:%M:%S
	utc true
  </parse>
</source>
<filter lm.*>
     @type record_transformer
     <record>
         _lm.resourceId {"system.hostname" : "10.52.128.17"}
         tag lm.filter
 </record>
</filter>
# Match events tagged with "lm.**" and send them to LogicMonitor
<match lm.**>
    @type lm
    company_name "lmcameroncompton"
    access_id "removed"
    access_key "removed"
      <buffer>
        @type memory
        flush_interval 1s
        chunk_limit_size 5m
      </buffer> 
    debug true
    compression gzip
</match>
```

If you want to map logs dynamically, you can 
`resource_mapping {"hostname": "system.sysname", "key_in_log" : "Property_key_in_lm"}`
This will result in : 

if log : { "message" : "message", "host": "55.10.10.1", "key_in_log": "value", "timestamp" : ..........}

The log will be mapped against a device in LM which is uniquely identifiable by property ****system.sysname = 55.10.10.1** **and** Property_key_in_lm= value**

**Comment by siddharthck** [comment]
Closing this issue as it looks like a solvable with correct config .
